### PR TITLE
Add CloseWorkflowRemoveIncompatibleDecisionInterceptor

### PR DESCRIPTION
**Pull request by ryanbrainard**
To break an import cycle (and put code where it really belongs), move the `CloseWorkflowRemoveIncompatibleDecisionInterceptor` into swfsm. Also exposes `CloseDecisionTypes` and `CloseDecisionIncompatableDecisionTypes` for tests to access.

### CODE REVIEW

File: fsm/interceptors.go [hunk 1]
```diff
@@ -429,3 +429,52 @@ func (s *StartCancelPair) decisionsContainStartCancel(in []*swf.Decision, cancel
...
+		// swf.DecisionTypeContinueAsNewWorkflowExecution is technically a close type,
+		// but swfsm currently doesn't really treat it as one and there's
+		// a lot of special logic, so excluding it from here for now
+	}
+}
+
+func CloseDecisionIncompatableDecisionTypes() []string {
+	return []string{
+		// TODO: flush out this list with other incompatible types
+		// TODO: see https://console.aws.amazon.com/support/home?#/case/?caseId=5223303261&displayId=5223303261&language=en
```
Comment (ricardochimal) [inline fsm/interceptors.go]: any more todos to finish up?

Comment (ricardochimal) [inline fsm/interceptors.go]: is there any more `TODO` here or can it be removed?

Comment (ryanbrainard) [reply fsm/interceptors.go]: I'm still waiting for AWS to respond this. There's no docs, so I'm guessing they're having to work with the dev team to get this info from the code. I'm thinking we should merge this as-is and then add the others once they respond.

**Comment by iancoffey** [comment]
This looks great. Does the test you used for reproduction in [#1941](https://github.com/heroku/dogwood/pull/1941#issue-202140627) now succeed?

**Comment by ryanbrainard** [comment]
@iancoffey Yes, the test passes using this interceptor. It was introduced in https://github.com/heroku/dogwood/pull/1941/commits/922cf709c984866708def161a795ec1a0f118f22 (failed on Travis due to import cycle) and then extracted to swfsm in https://github.com/heroku/dogwood/pull/1941/commits/f5b37c655a3751e41a17d65d1b122d3f8cb626d1 and it passes.
